package de.klg71.keycloakmigration.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties

@JsonIgnoreProperties(ignoreUnknown = true)
data class Realm(val id: String,
                 val realm: String,
                 var displayName: String?,
                 var displayNameHtml: String?,
                 val notBefore: Int,
                 val revokeRefreshToken: Boolean,
                 val refreshTokenMaxReuse: Int,
                 val accessTokenLifespan: Int,
                 val accessTokenLifespanForImplicitFlow: Int,
                 val ssoSessionIdleTimeout: Int,
                 val ssoSessionMaxLifespan: Int,
                 val ssoSessionIdleTimeoutRememberMe: Int,
                 val ssoSessionMaxLifespanRememberMe: Int,
                 val offlineSessionIdleTimeout: Int,
                 val offlineSessionMaxLifespanEnabled: Boolean,
                 val offlineSessionMaxLifespan: Int,
                 val accessCodeLifespan: Int,
                 val accessCodeLifespanUserAction: Int,
                 val accessCodeLifespanLogin: Int,
                 val actionTokenGeneratedByAdminLifespan: Int,
                 val actionTokenGeneratedByUserLifespan: Int,
                 val enabled: Boolean,
                 val sslRequired: String,
                 val registrationAllowed: Boolean,
                 val registrationEmailAsUsername: Boolean,
                 val rememberMe: Boolean,
                 val verifyEmail: Boolean,
                 val loginWithEmailAllowed: Boolean,
                 val duplicateEmailsAllowed: Boolean,
                 val resetPasswordAllowed: Boolean,
                 val editUsernameAllowed: Boolean,
                 val bruteForceProtected: Boolean,
                 val permanentLockout: Boolean,
                 val maxFailureWaitSeconds: Int,
                 val minimumQuickLoginWaitSeconds: Int,
                 val waitIncrementSeconds: Int,
                 val quickLoginCheckMilliSeconds: Int,
                 val maxDeltaTimeSeconds: Int,
                 val failureFactor: Int,
                 val defaultRoles: List<String>,
                 val requiredCredentials: List<String>,
                 val otpPolicyType: String,
                 val otpPolicyAlgorithm: String,
                 val otpPolicyInitialCounter: Int,
                 val otpPolicyDigits: Int,
                 val otpPolicyLookAheadWindow: Int,
                 val otpPolicyPeriod: Int,
                 val otpSupportedApplications: List<String>,
                 val webAuthnPolicyRpEntityName: String,
                 val webAuthnPolicySignatureAlgorithms: List<String>,
                 val webAuthnPolicyRpId: String,
                 val webAuthnPolicyAttestationConveyancePreference: String,
                 val webAuthnPolicyAuthenticatorAttachment: String,
                 val webAuthnPolicyRequireResidentKey: String,
                 val webAuthnPolicyUserVerificationRequirement: String,
                 val webAuthnPolicyCreateTimeout: Int,
                 val webAuthnPolicyAvoidSameAuthenticatorRegister: Boolean,
                 val webAuthnPolicyAcceptableAaguids: List<String>,
                 val browserSecurityHeaders: Map<String, String>,
                 val smtpServer: Map<String, String>,
                 val eventsEnabled: Boolean,
                 val eventsListeners: List<String>,
                 val enabledEventTypes: List<String>,
                 val adminEventsEnabled: Boolean,
                 val adminEventsDetailsEnabled: Boolean,
                 val internationalizationEnabled: Boolean,
                 val supportedLocales: List<String>,
                 val browserFlow: String,
                 val registrationFlow: String,
                 val directGrantFlow: String,
                 val resetCredentialsFlow: String,
                 val clientAuthenticationFlow: String,
                 val dockerAuthenticationFlow: String,
                 val attributes: Map<String, String>,
                 val userManagedAccessAllowed: Boolean
)
