package de.klg71.keycloakmigration.keycloakapi.model

data class AddClient(
        val clientId: String,
        val name: String? = null,
        val description: String? = null,
        val baseUrl: String? = null,
        val surrogateAuthRequired: Boolean,
        val enabled: Boolean,
        val clientAuthenticatorType: String,
        val redirectUris: List<String>,
        val webOrigins: List<String>,
        val notBefore: Int,
        val bearerOnly: Boolean,
        val consentRequired: Boolean,
        val standardFlowEnabled: Boolean,
        val implicitFlowEnabled: Boolean,
        val directAccessGrantsEnabled: Boolean,
        val serviceAccountsEnabled: Boolean,
        val publicClient: Boolean,
        val frontchannelLogout: Boolean,
        val protocol: String? = null,
        val attributes: Map<String, String>,
        val authenticationFlowBindingOverrides: Map<String, List<String>>,
        var authorizationServicesEnabled: Boolean,
        val fullScopeAllowed: Boolean,
        val nodeReRegistrationTimeout: Int,
        val protocolMappers: List<ProtocolMapper>? = null,
        val defaultClientScopes: List<String>,
        val optionalClientScopes: List<String>,
        val access: ClientAccess,
        val adminUrl: String? = null,
        val rootUrl: String? = null)
